name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Ou la version de PHP que vous utilisez
          extensions: mbstring, xml, curl, gd, mysqlnd, zip, dom # Les extensions PHP nécessaires à Laravel
          coverage: none #  Peut être 'pcov' ou 'xdebug' si vous voulez la couverture de code

      - name: Run Tests
        run:cd projet
	run: php artisan test
